
name: hello_world App Compiles (ubuntu-latest gcc)
on:
  pull_request:
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtsvg
      - uses: actions/checkout@v2
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: patch_conan
        run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - id: run_conan
        run: cd ${GITHUB_WORKSPACE}/example/exampleWidgetQt && conan install --generator cmake_find_package --install-folder ../build/conan-dependencies .
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/example/exampleWidgetQt && cmake -B../build -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/example/build && make
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: ./docs/code/doxyfile # default is ./Doxyfile
          # Working directory
          working-directory: . # default is .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
