
name: App Compiles
on:
  pull_request:
  push:
    branches: darshil-gtest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtsvg
      - uses: actions/checkout@v2
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: patch_conan
        run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - id: run_conan
        run: cd "${GITHUB_WORKSPACE}"/example/exampleWidgetQt && conan install --generator cmake_find_package --install-folder ../build/conan-dependencies .
      - id: cmake
        run: cd "${GITHUB_WORKSPACE}"/example/exampleWidgetQt && cmake -B../build -S.
      - id: make
        run: cd "${GITHUB_WORKSPACE}"/example/build && make
      - name: Install gtest
        run: |
          cd ~
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
          make -j8
          sudo make install
          sudo ldconfig
      - name: Run Tests
        run: |
          mkdir build
          cd build && ctest
          #cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..
          #make
          #/home/runner/work/github_actions_gtest_example/github_actions_gtest_example/build/test/github_actions_gtest_example.test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          VALIDATE_CLANG_FORMAT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doxygenize
        uses: langroodi/doxygenize@v1.7.0
        with:
          # Doxygen configuration file path
          doxygenconf: ./docs/code/doxyfile
          # Generated HTML documents output folder
          htmloutput: ./docs
          darkmode: true
